name: Test, Build, Deployment, Tweet
on: 
  push:
    branches:
      - master
jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        testMode:
          - playmode
          # - editmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          # path: /Library
          # key: Library -
          # path: ${{ matrix.projectPath }}/Library
          # key: Library -${{ matrix.projectPath }}
          path: Library
          key: Library
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        continue-on-error: true
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.11f1
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}
  buildForWebGL:
    name: Build for WebGL
    needs: testAllModes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-WebGL
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v2
        with:
          name: Build-WebGL
          path: build/WebGL
  deployPages:
    needs: buildForWebGL
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: Build-WebGL
          path: build

      - name: Display structure of root files
        run: ls -R
        working-directory: build/WebGL

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL
  tweet:
    needs: deployPages
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: snow-actions/tweet@v1.3.0
        with:
          status: |
            Hi Gamer, there is some good news :)

            We're happy to announce the new update: 
            
            ${{ github.event.head_commit.message }}
            
            You can access the game on: https://tikugler.github.io/skin-clicker-github
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

