on: 
  push:
    branches:
      - master
name: Twitter, together!
jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: snow-actions/tweet@v1.3.0
        with:
          status: |
            Hi Gamer, there is some good news :)

            We're happy to announce the new update: 
            
            ${{ github.event.head_commit.message }}
            
            You can access the game on: https://tikugler.github.io/skin-clicker-github
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}